---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foo--bar
type: Opaque
data:
# accessKeyID: base64(access-key-id)
# secretAccessKey: base64(secret-access-key)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foo--bar
spec:
  cloudProfile:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: CloudProfile
  seed:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Seed
  shoot:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Shoot
    spec:
      cloud:
        metal:
          networks:
            pods: 10.250.0.0/19
      kubernetes:
        version: 1.13.4
      hibernation:
        enabled: false
    status:
      lastOperation:
        state: Succeeded
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: ControlPlane
metadata:
  name: control-plane
  namespace: shoot--foo--bar
spec:
  type: metal
  region: eu-west-1
  secretRef:
    name: cloudprovider
    namespace: shoot--foo--bar
  providerConfig:
    apiVersion: metal.provider.extensions.gardener.cloud/v1alpha1
    kind: ControlPlaneConfig
    cloudControllerManager:
      featureGates:
        CustomResourceValidation: true
  infrastructureProviderStatus:
    apiVersion: metal.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
    vpc:
      id: vpc-1234
      subnets:
      - id: subnet-acbd1234
        purpose: public
        zone: eu-west-1a
