---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foo--bar
type: Opaque
data:
  metalAPIKey: abc
  metalAPIHMac: cdf
  metalAPIURL: ghj

---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foo--bar
spec:
  cloudProfile:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: CloudProfile
  seed:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Seed
  shoot:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Shoot
    status:
      lastOperation:
        state: Succeeded
---
# This resource does result in the deployment of the machine-controller-manager, the machine classes,
# and the desired MachineDeployments. However, it does not create actual virtual machines because the
# provided infrastructure status data (subnet id, etc.) is not valid/does not exist.
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Worker
metadata:
  name: worker
  namespace: shoot--foo--bar
spec:
  type: metal
  region: nbg
  secretRef:
    name: cloudprovider
    namespace: shoot--foo--bar
  infrastructureProviderStatus:
    apiVersion: metal.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
  pools:
  - name: cpu-worker
    machineType: c1-xlarge-x86
    machineImage:
      name: ubuntu
      version: "19.04"
    minimum: 1
    maximum: 1
    maxSurge: 1
    maxUnavailable: 0
  # labels:
  #   key: value
  # annotations:
  #   key: value
  # taints: # See also https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  # - key: foo
  #   value: bar
  #   effect: NoSchedule
    userData: IyEvYmluL2Jhc2gKCmVjaG8gImhlbGxvIHdvcmxkIgo=
    zones:
    - nbg-w8101
