required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen"
]

[[override]]
  name = "github.com/gardener/gardener-extensions"
  revision = "2faeebd1c00c8325d2c2d9996217349e45c20dbf"
  #version = "0.7.4"

[[override]]
  name = "github.com/gardener/gardener-resource-manager"
  revision = "e0f770704e8c97f8a4a5003f14d88a1ae55253a1"

[[override]]
  name = "github.com/gardener/gardener"
  revision = "641367fd36d54086712027f337effcb6c9f950cf"
  #revision = "c6b7b89a41eed319ac467ad2f448b3337d506dd7"
  #source = "github.com/metal-pod/gardener"

[[override]]
  name = "github.com/pkg/errors"
  revision = "816c9085562cd7ee03e7f8188a1cfd942858cded"

[[override]]
  name = "github.com/gardener/machine-controller-manager"
  revision = "11ed8d959f15e9e60d63333a8d6c863402fd647f"
  source = "github.com/metal-pod/machine-controller-manager"

# use the same version that is referenced by k8s.io/apiserver
[[override]]
  name = "github.com/docker/docker"
  revision = "a9fbbdc8dd8794b20af358382ab780559bca589d"

# use the same version that is referenced by k8s.io, mainly required by Helm
# https://github.com/kubernetes/kubernetes/blob/v1.13.5/Godeps/Godeps.json
[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

[[override]]
  name = "github.com/jmespath/go-jmespath"
  version = "^0.2.2"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.21.9"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "v19"

# Dependencies for testing purposes only

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.4.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false

  [[prune.project]]
    name = "github.com/golang/mock"
    unused-packages = false
