machineClasses:
- name: class-1
  partition: nbg-w8101
  apiURL: https://metal-api
  size: c1-xlarge-x86
  project: gardener-test
  network: private-network-id
  image: ubuntu-19.04
  sshkeys: []
  tags:
    - gardener=something
  secret:
    cloudConfig: abc
    metalAPIKey: abc
    metalAPIHMac: abc
