machineClasses:
- name: class-1
  partition: nbg-w8101
  size: c1-xlarge-x86
  image: ubuntu-19.04
  project: gardener-test
  tenant: devops
  sshkeys: []
  tags:
    - gardener
  secret:
    cloudConfig: abc
    metalAPIKey: abc
    metalAPIHMac: abc
    metalAPIURL: abc
