{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    garden.sapcloud.io/purpose: machineclass
type: Opaque
data:
  userData: {{ $machineClass.secret.cloudConfig | b64enc }}
  metalAPIKey: {{ $machineClass.secret.metalAPIKey | b64enc }}
  metalAPIHMac: {{ $machineClass.secret.metalAPIHMac | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: MetalMachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  apiURL: {{ $machineClass.apiURL }}
  partition: {{ $machineClass.partition }}
  size: {{ $machineClass.size }}
  image: {{ $machineClass.image }}
  project: {{ $machineClass.project }}
  network: {{ $machineClass.network }}
  sshKeys: 
{{ toYaml $machineClass.sshkeys | indent 4 }}
  secretRef:
    name: {{ $machineClass.name }}
    namespace: {{ $.Release.Namespace }}
{{- if $machineClass.tags }}
  tags:
{{ toYaml $machineClass.tags | indent 4 }}
{{- end }}
{{- end }}