---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machines.machine.sapcloud.io
spec:
  group: machine.sapcloud.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Machine
    plural: machines
    singular: machine
    shortNames:
    - mach
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Status
    type: string
    description: Current status of the machine.
    JSONPath: .status.currentStatus.phase
  - name: Age
    type: date
    description: >
      CreationTimestamp is a timestamp representing the server time when this object was created.
      It is not guaranteed to be set in happens-before order across separate operations.
      Clients may not set this value. It is represented in RFC3339 form and is in UTC.
      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    JSONPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machinesets.machine.sapcloud.io
spec:
  group: machine.sapcloud.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: MachineSet
    plural: machinesets
    singular: machineset
    shortNames:
    - machset
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Desired
    type: integer
    description: Number of desired replicas.
    JSONPath: .spec.replicas
  - name: Current
    type: integer
    description: Number of actual replicas.
    JSONPath: .status.replicas
  - name: Ready
    type: integer
    description: Number of ready replicas for this machine set.
    JSONPath: .status.readyReplicas
  - name: Age
    type: date
    description: >
      CreationTimestamp is a timestamp representing the server time when this object was created.
      It is not guaranteed to be set in happens-before order across separate operations.
      Clients may not set this value. It is represented in RFC3339 form and is in UTC.
      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    JSONPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machinedeployments.machine.sapcloud.io
spec:
  group: machine.sapcloud.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: MachineDeployment
    plural: machinedeployments
    singular: machinedeployment
    shortNames:
    - machdeploy
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Ready
    type: integer
    description: Total number of ready machines targeted by this machine deployment.
    JSONPath: .status.readyReplicas
  - name: Desired
    type: integer
    description: Number of desired machines.
    JSONPath: .spec.replicas
  - name: Up-to-date
    type: integer
    description: Total number of non-terminated machines targeted by this machine deployment that have the desired template spec.
    JSONPath: .status.updatedReplicas
  - name: Available
    type: integer
    description: Total number of available machines (ready for at least minReadySeconds) targeted by this machine deployment.
    JSONPath: .status.availableReplicas
  - name: Age
    type: date
    description: >
      CreationTimestamp is a timestamp representing the server time when this object was created.
      It is not guaranteed to be set in happens-before order across separate operations.
      Clients may not set this value. It is represented in RFC3339 form and is in UTC.
      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    JSONPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: metalmachineclasses.machine.sapcloud.io
spec:
  group: machine.sapcloud.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: MetalMachineClass
    plural: metalmachineclasses
    singular: metalmachineclass
    shortNames:
    - metalcls
  subresources:
    status: {}
