{{- if .Values.accountingExporter.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: accounting-exporter
  name: accounting-exporter-tls
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.pem: {{ required ".Values.accountingExporter.accountingAPI.ca is required" (b64enc .Values.accountingExporter.accountingAPI.ca) }}
  client.pem: {{ required ".Values.accountingExporter.accountingAPI.cert is required" (b64enc .Values.accountingExporter.accountingAPI.cert) }}
  client-key.pem: {{ required ".Values.accountingExporter.accountingAPI.certKey is required" (b64enc .Values.accountingExporter.accountingAPI.certKey) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: accounting-exporter
spec:
  selector:
    matchLabels:
      k8s-app: accounting-exporter
  template:
    metadata:
      labels:
        k8s-app: accounting-exporter
        app: accounting-exporter
        networking.gardener.cloud/from-prometheus: allowed
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
        networking.gardener.cloud/to-public-networks: allowed
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - image: {{ index .Values.images "accounting-exporter" }}
        imagePullPolicy: Always
        name: accounting-exporter
        env:
        - name: KUBE_COUNTER_PARTITION
          value: {{ .Values.accountingExporter.enrichments.partitionID }}
        - name: KUBE_COUNTER_TENANT
          value: {{ .Values.accountingExporter.enrichments.tenant }}
        - name: KUBE_COUNTER_PROJECT_ID
          value: {{ .Values.accountingExporter.enrichments.projectID }}
        - name: KUBE_COUNTER_CLUSTER_ID
          value: {{ .Values.accountingExporter.enrichments.clusterID }}
        - name: KUBE_COUNTER_CLUSTER_NAME
          value: {{ .Values.accountingExporter.enrichments.clusterName }}
        - name: KUBE_COUNTER_KUBECONFIG
          value: /var/lib/accounting-exporter/kubeconfig
        - name: KUBE_COUNTER_ACCOUNTING_API_HOSTNAME
          value: {{ .Values.accountingExporter.accountingAPI.hostname }}
        - name: KUBE_COUNTER_ACCOUNTING_API_PORT
          value: "{{ .Values.accountingExporter.accountingAPI.port }}"
        - name: KUBE_COUNTER_NETWORK_TRAFFIC_ENABLED
          value: "{{ .Values.accountingExporter.networkTraffic.enabled }}"
        volumeMounts:
        - name: accounting-exporter
          mountPath: /var/lib/accounting-exporter
        - mountPath: /certs
          name: certs
      restartPolicy: Always
      volumes:
      - name: accounting-exporter
        secret:
          secretName: accounting-exporter
      - name: certs
        secret:
          secretName: accounting-exporter-tls
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-allow-accounting-api
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      k8s-app: accounting-exporter
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 9000
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: egress-allow-accounting-api
  namespace: firewall
spec:
  egress:
  - ports:
    - port: 9000
      protocol: TCP
    to:
    - cidr: 0.0.0.0/0
{{- end }}
