---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: accounting-exporter
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - persistentvolumes
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: accounting-exporter
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: accounting-exporter
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: accounting-exporter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: accounting-exporter
spec:
  selector:
    matchLabels:
      k8s-app: accounting-exporter
  template:
    metadata:
      labels:
        k8s-app: accounting-exporter
        app: accounting-exporter
        networking.gardener.cloud/from-prometheus: allowed
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
        networking.gardener.cloud/to-public-networks: allowed
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - image: {{ index .Values.images "accounting-exporter" }}
        imagePullPolicy: Always
        name: accounting-exporter
        env:
        - name: KUBE_COUNTER_PARTITION
          value: {{ .Values.accex_partitionID }}
        - name: KUBE_COUNTER_TENANT
          value: {{ .Values.accex_tenant }}
        - name: KUBE_COUNTER_PROJECT_ID
          value: {{ .Values.accex_projectID }}
        - name: KUBE_COUNTER_PROJECT_NAME
          value: {{ .Values.accex_projectname }}
        - name: KUBE_COUNTER_CLUSTER_ID
          value: {{ .Values.accex_clusterID}}
        - name: KUBE_COUNTER_CLUSTER_NAME
          value: {{ .Values.accex_clustername}}
        - name: KUBE_COUNTER_KUBECONFIG
          value: /var/lib/accounting-exporter/kubeconfig
        - name: KUBE_COUNTER_SINK_URL
          value: {{ .Values.accex_accountingsink_url }}
        - name: KUBE_COUNTER_SINK_HMAC
          value: {{ .Values.accex_accountingsink_HMAC }}
        volumeMounts:
        - name: accounting-exporter
          mountPath: /var/lib/accounting-exporter
      restartPolicy: Always
      volumes:
      - name: accounting-exporter
        secret:
          secretName: accounting-exporter
