apiVersion: apps/v1
kind: Deployment
metadata:
  name: limit-validating-webhook
  namespace: kube-system
  labels:
    app: limit-validating-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limit-validating-webhook
  template:
    metadata:
      labels:
        app: limit-validating-webhook
    spec:
      containers:
        - name: limit-validating-webhook
          image: {{ index .Values.images "limit-validating-webhook" }}
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -excludedNamespaces=kube-system
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: limit-validating-webhook-server
