apiVersion: v1
kind: Service
metadata:
  name: limit-validating-webhook
  namespace: kube-system
  labels:
    app: limit-validating-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: limit-validating-webhook
