---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-vpn
  namespace: firewall
spec:
  egress:
  - ports:
    - port: 4314
      protocol: UDP
    - port: 4314
      protocol: TCP
    to:
    - cidr: 0.0.0.0/0
