
---
apiVersion: v1
kind: Namespace
metadata:
  name: firewall
---
apiVersion: metal-stack.io/v1
kind: Firewall
metadata:
  namespace: firewall
  name: firewall
spec:
  enabled: true
  interval: {{ .Values.firewall.interval }}
  dryrun: false
{{- if gt (len .Values.firewall.internalPrefixes) 0 -}}
  internalprefixes:
    {{ toYaml .Values.firewall.internalPrefixes | indent 4 }}
{{- end -}}
