
---
apiVersion: v1
kind: Namespace
metadata:
  name: firewall
---
apiVersion: metal-stack.io/v1
kind: Firewall
metadata:
  namespace: firewall
  name: firewall
spec:
  enabled: true
  interval: 10s
  dryrun: false
