images:
- name: metalccm
  sourceRepository: github.com/metal-stack/metal-ccm
  repository: metalstack/metal-ccm
  tag: v0.3.0
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "0.26.3"
- name: droptailer
  sourceRepository: github.com/metal-stack/droptailer
  repository: metalstack/droptailer-server
  tag: v0.2.1
- name: csi-lvm-controller
  sourceRepository: github.com/metal-stack/csi-lvm-controller
  repository: metalstack/csi-lvm-controller
  tag: v0.5.0
- name: csi-lvm-provisioner
  sourceRepository: github.com/metal-stack/csi-lvm-provisioner
  repository: metalstack/csi-lvm-provisioner
  tag: v0.5.0
- name: metallb-speaker
  sourceRepository: https://github.com/metallb/metallb
  repository: metallb/speaker
  tag: v0.8.3
- name: metallb-controller
  sourceRepository: https://github.com/metallb/metallb
  repository: metallb/controller
  tag: v0.8.3

# can be provided via image override:
# - name: authn-webhook
#   sourceRepository:
#   repository:
#   tag:
# - name: group-rolebinding-controller
#   sourceRepository:
#   repository:
#   tag:
# - name: accounting-exporter
#   sourceRepository:
#   repository:
#   tag:
