replicas: 1
kubernetesVersion: 1.7.5
projectID: project-id
partitionID: partition-id
networkID: network-id
podNetwork: 192.168.0.0/16
environment: []
additionalParameters: []
podAnnotations: {}
featureGates: {}
  # CustomResourceValidation: true
  # RotateKubeletServerCertificate: false
images: 
  metalccm: image-repository:image-tag
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 300Mi


#
# webhook
#
tenant: someTenant
clustername: projectID

oidcIssuerUrl: https://tokenissuer/dex
oidcIssuerClientId: myClientId
