---
limitValidatingWebhook_caBundle: ABCDEF
limitValidatingWebhook_url: https://replace-this-webhook/validate

images: 
    droptailer: image-repository:image-tag
    metallb-speaker: image-repository:image-tag
    metallb-controller: image-repository:image-tag
