---
images:
    droptailer: image-repository:image-tag
    metallb-speaker: image-repository:image-tag
    metallb-controller: image-repository:image-tag

firewallSpec:
    interval: 10s
    dryrun: false
    ipv4rulefile: /etc/
    rateLimits: []
    internalprefixes: []
    egressRules:
    - networkid: internet
      ips:
      - 212.34.83.15
    firewallNetworks: []

accountingExporter:
    enabled: false

groupRolebindingController:
    enabled: false

limitValidatingWebhook:
    enabled: false
    ca: ABCDEF
    url: https://replace-this-webhook/validate
