---
images:
    droptailer: image-repository:image-tag
    metallb-speaker: image-repository:image-tag
    metallb-controller: image-repository:image-tag

firewall:
    interval: 10s
    internalPrefixes: []
    rateLimits: []

accountingExporter:
    enabled: false

groupRolebindingController:
    enabled: false

limitValidatingWebhook:
    enabled: false
    ca: ABCDEF
    url: https://replace-this-webhook/validate

splunkAuditWebhook:
    enabled: false
    url: https://splunk-audit-webhook.shoot--local--myshootname.svc.cluster.local/audit
    ca: ABCDEF
