---
kubernetesVersion: 1.7.5
featureGates: {}

images:
  metalccm: image-repository:image-tag
  authn-webhook: image-repository:image-tag
  splunk-audit-webhook: image-repository:image-tag
  group-rolebinding-controller: image-repository:image-tag
  accounting-exporter: image-repository:image-tag
  limit-validating-webhook: image-repository:image-tag

cloudControllerManager:
  additionalParameters: []
  podAnnotations: {}
  replicas: 1
  podNetwork: 192.168.0.0/16
  projectID: project-id
  partitionID: partition-id
  networkID: network-id
  clusterID: cluster-id
  metal:
    endpoint: api-url
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 300Mi

groupRolebindingController:
  enabled: false
  clusterName: cluster-name

authnWebhook:
  enabled: false
  port: 443
  debug: true
  tenant: some-tenant
  providerTenant: provider-tenant
  clusterName: cluster-name
  oidc:
    issuerUrl: https://tokenissuer/dex
    issuerClientId: myClientId

splunkAuditWebhook:
  enabled: false
  port: 3000
  acceptInsecureCert: false
  endpointRequiresClientCert: false
  hecEndpoint:
    url: https://splunk.example.org/
    token: "Token_00000000-0000-0000-0000-000000000000"

limitValidatingWebhook:
  enabled: false

accountingExporter:
  enabled: false
  enrichments:
    projectID: project-id
    partitionID: partition-id
    tenant: some-tenant
    clusterID: cluster-id
    clusterName: cluster-name
  networkTraffic:
    enabled: false
  accountingAPI:
    hostname: hostname
    port: 9000
    ca: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    cert: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    certKey: |
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----
