{{- if .Values.limitValidatingWebhook.enabled }}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: limit-validating-webhook
  labels:
    app: limit-validating-webhook
webhooks:
- name: limit-validating-webhook.metal-stack.io
  clientConfig:
    url: {{ .Values.limitValidatingWebhook.url }}
    caBundle: {{ .Values.limitValidatingWebhook.ca }}
  rules:
  - operations: ["CREATE"]
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["containers","pods","deployments","daemonsets","statefulsets","replicasets","replicationcontrollers","jobs","cronjobs"]
{{- end }}
