apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: limit-validating-webhook
  labels:
    app: limit-validating-webhook
webhooks:
- name: limit-validating-webhook.metal-pod.io
  clientConfig:
    service:
      name: limit-validating-webhook
      namespace: kube-system
      path: "/validate"
    caBundle: {{ .Values.limitValidatingWebhook_caBundle }}
  rules:
  - operations: ["CREATE"]
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["containers","pods","deployments","daemonsets","statefulsets","replicasets","replicationcontrollers","jobs","cronjobs"]
