---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-vpn
  namespace: firewall
spec:
  egress:
  - ports:
    - port: 4314
      protocol: UDP
    - port: 4314
      protocol: TCP
    to:
    - cidr: 0.0.0.0/0
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-dns
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-https
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-http
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 80
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-ntp
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 123
---
# currently, apiserver SNI is behind a feature gateway but will probably graduate in the future
# see https://github.com/gardener/gardener/blob/master/docs/proposals/08-shoot-apiserver-via-sni.md
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-apiserver-sni
  namespace: firewall
spec:
  egress:
  - ports:
    - port: 8443
      protocol: TCP
    to:
    - cidr: 0.0.0.0/0
