apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-init
  namespace: kube-system
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: node-init
spec:
  allowPrivilegeEscalation: true
  privileged: true
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
  hostNetwork: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-system:node-init
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - node-init
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-system:node-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-system:node-init
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: node-init
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-init
  namespace: kube-system
  labels:
    app: node-init
spec:
  selector:
    matchLabels:
      app: node-init
  template:
    metadata:
      labels:
        app: node-init
    spec:
      serviceAccount: node-init
      serviceAccountName: node-init
      containers:
      - name: node-init-pause
        image: k8s.gcr.io/pause:3.3
        securityContext:
          privileged: true
      initContainers:
      - name: node-init
        image: busybox:stable
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        command: ['sh', '-c', "\
          wget -qO /tmp/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/linux/amd64/kubectl ; \
          chmod 755 /tmp/kubectl; \
          POD_CIDR=$(/tmp/kubectl get node $KUBE_NODE_NAME -o jsonpath='{.spec.podCIDR}'); \
          ip route add $POD_CIDR dev lo || true;\
        "]
        securityContext:
          privileged: true
      hostNetwork: true
