---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp.metallb
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
spec:
  allowedCapabilities:
  - NET_RAW
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes: 
  - secret
