---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:firewall-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal-stack.io/v1
  resources:
  - clusterwidenetworkpolicy
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apigroups:
  - metal-stack.io/v1
  resources:
  - firewall
  - networkids
  - networktraffic
  verbs:
  - get
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:firewall-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:firewall-controller
subjects:
- kind: User
  name: system:firewall-controller
  apiGroup: ""
