name: Build image from pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: env

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      if: github.repository == 'metal-stack/gardener-extension-provider-metal'

    - name: Check (lint) and Test
      run: |
        make test-in-docker

    - name: Build and push Docker image
      run: |
        export GITHUB_TAG_NAME=${GITHUB_HEAD_REF##*/}
        make docker-image
        make docker-push
      if: github.repository == 'metal-stack/gardener-extension-provider-metal'
