name: Build image from pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and push Docker image
      run: |
        # pull request images are prefixed with 'pr' to prevent them from overriding released images
        export GITHUB_TAG_NAME=pr-${GITHUB_HEAD_REF##*/}
        docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
        make docker-image
        make docker-push