name: Build image from release tag

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check (lint) and Test
      run: |
        make test-in-docker
    - name: Build and push Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        export GITHUB_TAG_NAME=${GITHUB_REF##*/}
        make docker-image
        make docker-push
